server {
  listen 80;

  resolver 127.0.0.11 valid=30s;

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  location /api/accounts {
    proxy_pass http://account-service:4001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/transactions {
    proxy_pass http://transaction-service:4002;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  
  location /api/auth {
    proxy_pass http://auth-service:4005;
    proxy_set_header Host $host;
  }
}